### ISSUE TITLE
Filter Transactions

### ISSUE THREAD

**Issue by InsouciantQualms** [justbudget/justbudget#43] opened 2022-06-09 12:32 UTC
Use Case:

I would like the ability to hide pending transactions and separate to hide reconciled transactions.  Each account would persist the filtering preference and could be set separately.  Adding the ability to filter by dates would also be useful.

**Comment by justbudget** [comment] 2022-06-09 13:05
Thanks for the note, I think this is related to https://github.com/justbudget/justbudget/issues/11

But also your note about "persisting filtering preference" is a good addition to https://github.com/justbudget/justbudget/issues/6

**Comment by justbudget** [comment] 2022-08-17 19:21
I added a note to https://github.com/justbudget/justbudget/issues/11 specifying that the filters should persist. Knowing that, I'm going to close this as a duplicate of https://github.com/justbudget/justbudget/issues/11

**Closed as completed by justbudget** 2022-08-17 19:21 UTC
